name: agreya_coffee
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  cached_network_image: ^3.2.1
  chucker_flutter: 1.7.2
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_svg: ^2.0.5
  get_it: ^7.2.0
  go_router: ^14.6.3
  intl: ^0.19.0
  json_annotation: ^4.8.0
  pretty_dio_logger: ^1.3.1
  sticky_headers: ^0.3.0+2

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.13.1
  flutter_lorem: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.5.4
  lint: ^2.0.1
  mocktail: ^1.0.0
  retrofit_generator: ^7.0.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/images/svg/
